# Generated by Django 6.0.6 on 2026-06-14 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название задачи")),
                ("description", models.TextField(blank=True, verbose_name="Описание задачи")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Новая"), ("in_progress", "В работе"), ("completed", "Завершена")],
                        default="new",
                        max_length=20,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Низкий"), ("medium", "Средний"), ("high", "Высокий")],
                        default="medium",
                        max_length=20,
                        verbose_name="Приоритет задачи",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
    ]
